-- MySQL Script generated by MySQL Workbench
-- Tue Nov  2 15:11:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP USER IF EXISTS `iwa_2021`@`localhost`;
DROP USER IF EXISTS `iwa_2021`;
DROP SCHEMA IF EXISTS `iwa_2021_sk_projekt`;

-- ----------------------------------------------------- 
-- Schema iwa_2021_sk_projekt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iwa_2021_sk_projekt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iwa_2021_sk_projekt` DEFAULT CHARACTER SET utf8 ;
USE `iwa_2021_sk_projekt` ;

-- -----------------------------------------------------
-- Table `iwa_2021_sk_projekt`.`tip_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwa_2021_sk_projekt`.`tip_korisnika` (
  `tip_korisnika_id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`tip_korisnika_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwa_2021_sk_projekt`.`znanstveno_podrucje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwa_2021_sk_projekt`.`znanstveno_podrucje` (
  `znanstveno_podrucje_id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) NOT NULL,
  `opis` TEXT NOT NULL,
  PRIMARY KEY (`znanstveno_podrucje_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwa_2021_sk_projekt`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwa_2021_sk_projekt`.`korisnik` (
  `korisnik_id` INT NOT NULL AUTO_INCREMENT,
  `tip_korisnika_id` INT NOT NULL,
  `znanstveno_podrucje_id` INT NULL,
  `korime` VARCHAR(50) NOT NULL,
  `ime` VARCHAR(50) NOT NULL,
  `prezime` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `lozinka` VARCHAR(50) NOT NULL,
  `slika` TEXT NULL,
  `titula` VARCHAR(20) NULL,
  `radno_mjesto` VARCHAR(50) NULL,
  `opis` TEXT NULL,
  PRIMARY KEY (`korisnik_id`),
  INDEX `tip_korisnika_id_idx` (`tip_korisnika_id` ASC),
  INDEX `podrucje_id_idx` (`znanstveno_podrucje_id` ASC),
  CONSTRAINT `tip_korisnika_id_fk`
    FOREIGN KEY (`tip_korisnika_id`)
    REFERENCES `iwa_2021_sk_projekt`.`tip_korisnika` (`tip_korisnika_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `znanstveno_podrucje_id_fk_3`
    FOREIGN KEY (`znanstveno_podrucje_id`)
    REFERENCES `iwa_2021_sk_projekt`.`znanstveno_podrucje` (`znanstveno_podrucje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwa_2021_sk_projekt`.`komentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwa_2021_sk_projekt`.`komentar` (
  `komentar_id` INT NOT NULL AUTO_INCREMENT,
  `znanstveno_podrucje_id` INT NOT NULL,
  `korisnik_id` INT NOT NULL,
  `sadrzaj` TEXT NOT NULL,
  `datum_vrijeme_kreiranja` TIMESTAMP NOT NULL,
  `komentar_znanstvenika` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`komentar_id`),
  INDEX `korisnik_id_fk_idx` (`korisnik_id` ASC),
  INDEX `podrucje_id_fk_idx` (`znanstveno_podrucje_id` ASC),
  CONSTRAINT `znanstveno_podrucje_id_fk_1`
    FOREIGN KEY (`znanstveno_podrucje_id`)
    REFERENCES `iwa_2021_sk_projekt`.`znanstveno_podrucje` (`znanstveno_podrucje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `korisnik_id_fk`
    FOREIGN KEY (`korisnik_id`)
    REFERENCES `iwa_2021_sk_projekt`.`korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iwa_2021_sk_projekt`.`zahtjev_podrucja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iwa_2021_sk_projekt`.`zahtjev_podrucja` (
  `moderator_id` INT NOT NULL,
  `znanstveno_podrucje_id` INT NOT NULL,
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`moderator_id`, `znanstveno_podrucje_id`),
  INDEX `podrucje_id_fk_idx` (`znanstveno_podrucje_id` ASC),
  CONSTRAINT `moderator_id_fk`
    FOREIGN KEY (`moderator_id`)
    REFERENCES `iwa_2021_sk_projekt`.`korisnik` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `znanstveno_podrucje_id_fk_2`
    FOREIGN KEY (`znanstveno_podrucje_id`)
    REFERENCES `iwa_2021_sk_projekt`.`znanstveno_podrucje` (`znanstveno_podrucje_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'iwa_2021' IDENTIFIED BY 'foi2021';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `iwa_2021_sk_projekt`.* 
TO 'iwa_2021'@'localhost' IDENTIFIED BY 'foi2021';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
